### ISSUE TITLE
Organizasyon logosu

### ISSUE THREAD

**Issue by halilemreozen** [aydabir/aydabir#1]
Organizasyon logosu hakkında önerileri bulunan var mı ?

**Comment by halilemreozen** [comment]
Biraz javabucks reklamı gibi oldu ama her buluşmamız kafelerde olduğuna göre olabilir :

![](http://angelamccall.com/wp-content/uploads/2013/08/starbucks_coffee.png)

![](http://ellaknecht.com/wp-content/uploads/2015/04/starbucks_coffee_3.png)

![](https://pixabay.com/static/uploads/photo/2012/04/14/15/14/coffee-34251_960_720.png)

**Comment by gokhansolak** [comment]
İsimle uyumluluk açısından şöyle şeyler de olabilir. İlerleyen zamanlarda
çizeriz bir şeyler :)
11 Oca 2016 03:19 tarihinde "Halil Emre ÖZEN" notifications@github.com
yazdı:

Biraz javabucks reklamı gibi oldu ama her buluşmamız kafelerde olduğuna
göre olabilir :

https://camo.githubusercontent.com/afb0cd9a1b7a751b6b4e583cf36ca80851df14e1/687474703a2f2f616e67656c616d6363616c6c2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031332f30382f737461726275636b735f636f666665652e706e67

https://camo.githubusercontent.com/97df419cb499a6cc28289274ef4e4102e05162ee/68747470733a2f2f7777772e676f6f676c652e636f6d2e74722f75726c3f73613d69267263743d6a26713d26657372633d7326736f757263653d696d616765732663643d267665643d2675726c3d68747470253341253246253246616e67656c616d6363616c6c2e636f6d253246686f772d746f2d64657369676e2d612d6c6f676f2532462662766d3d62762e3131313339363038352c642e62476726707369673d4146516a434e4846474f7655426578754239796f784f4450513052655247466f7967267573743d31343532353630393538353736373533

https://camo.githubusercontent.com/ef94c6984ebf50a60a298a4b7a73fc69e827b40a/68747470733a2f2f706978616261792e636f6d2f7374617469632f75706c6f6164732f70686f746f2f323031322f30342f31342f31352f31342f636f666665652d33343235315f3936305f3732302e706e67
